import {createRequire} from "module";

const require = createRequire(import.meta.url);
const pkg = require("../package.json");
const {homepage, version} = pkg;

export const STATUS = "status";
export const BODY = "body";
export const HEADERS = "headers";
export const HEADER = "header";
export const VALUES = "values";
export const EMPTY = "";
export const USER_AGENT = "user-agent";
export const USER_AGENT_VALUE = `tiny-httptest bot/${version} (${homepage})`;
export const APPLICATION_JSON = "application/json";
export const TRUE = "true";
export const ACCESS_CONTROL_ALLOW_ORIGIN = "access-control-allow-origin";
export const ACCESS_CONTROL_REQUEST_HEADERS = "access-control-request-headers";
export const ACCESS_CONTROL_ALLOW_HEADERS = "access-control-allow-headers";
export const ACCESS_CONTROL_ALLOW_CREDENTIALS = "access-control-allow-credentials";
export const ACCESS_CONTROL_EXPOSE_HEADERS = "access-control-expose-headers";
export const CONTENT_TYPE = "content-type";
export const OPTIONS = "OPTIONS";
export const IF_NONE_MATCH = "if-none-match";
export const SET_COOKIE = "set-cookie";
export const DELIMITER = ":";
export const HTTP = "http";
export const UTF8 = "utf8";
export const DATA = "data";
export const END = "end";
export const ERROR = "error";
export const STRING = "string";
export const CONTENT_LENGTH = "content-length";
export const OBJECT = "object";
export const GET = "GET";
export const TIMEOUT = 30000;
export const LOCALHOST = "http://localhost";
export const INVALID_HTTP_METHOD = "Invalid HTTP method";
export const UNEXPECTED_TYPE_A_B = "Unexpected %TYPE value: %A !== %B";
export const TYPE = "%TYPE";
export const A = "%A";
export const B = "%B";
export const BASIC = "Basic %A";
